---

  - name: Make sure console utils are installed
    homebrew:
      name:
        - watchman
        - docker
        - docker-compose
        - pyenv

  - name: Make sure graphical utils are installed
    homebrew_cask:
      name:
        - visual-studio-code
        - iterm2
        # - android-studio # already installed manually

  - name: Install nvm
    shell: >
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    args:
      chdir: "~/"
      creates: "~/.nvm/nvm.sh"

  - name: Install poetry
    shell: >
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    environment:
      POETRY_VERSION: "1.1.5"
    args:
      creates: "~/.poetry/bin/poetry"
